name: slmbench-web
region: nyc
static_sites:
- name: slmbench-static
  github:
    repo: CycleCore-Technologies/slmbench
    branch: main
    deploy_on_push: true
  source_dir: /website
  output_dir: /templates
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
domains:
- domain: slmbench.com
  type: PRIMARY
  zone: slmbench.com
